In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_1=pd.read_csv("dataset_1 - dataset_1.csv")

In [3]:
dataset_1

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [4]:
dataset_1.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        1  01-01-2011       1   0     1   0    False        6           1   
1        2  01-01-2011       1   0     1   1    False        6           1   
2        3  01-01-2011       1   0     1   2    False        6           1   
3        4  01-01-2011       1   0     1   3    False        6           1   
4        5  01-01-2011       1   0     1   4    False        6           1   

   temp  
0  0.24  
1  0.22  
2  0.22  
3  0.24  
4  0.24

In [5]:
dataset_1.tail()

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20

#  *Checking Dimension of Dataset of dataset_1*


In [6]:
dataset_1.shape

(610, 10)

In [7]:
dataset_1.shape[0] # Provide only the number of rows

610

In [8]:
dataset_1.shape[1] # Provide only the number of columns

10

# *Datetype of Dataset_1*

In [9]:
dataset_1.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday          bool
weekday         int64
weathersit      int64
temp          float64
dtype: object

# *Unique values of Dataset_1*

In [10]:
dataset_1['weekday'].unique()

array([6, 0, 1, 2, 3, 4, 5])

# *Summary of Datatype_1*

In [11]:
dataset_1.describe()

instant  season     yr   mnth          hr     weekday  weathersit  \
count  610.000000   610.0  610.0  610.0  610.000000  610.000000  610.000000   
mean   305.500000     1.0    0.0    1.0   11.795082    2.977049    1.477049   
std    176.236111     0.0    0.0    0.0    6.852107    2.054943    0.643496   
min      1.000000     1.0    0.0    1.0    0.000000    0.000000    1.000000   
25%    153.250000     1.0    0.0    1.0    6.000000    1.000000    1.000000   
50%    305.500000     1.0    0.0    1.0   12.000000    3.000000    1.000000   
75%    457.750000     1.0    0.0    1.0   18.000000    5.000000    2.000000   
max    610.000000     1.0    0.0    1.0   23.000000    6.000000    4.000000   

             temp  
count  610.000000  
mean     0.196885  
std      0.081304  
min      0.020000  
25%      0.160000  
50%      0.200000  
75%      0.235000  
max      0.460000

In [12]:
dataset_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     610 non-null    int64  
 1   dteday      610 non-null    object 
 2   season      610 non-null    int64  
 3   yr          610 non-null    int64  
 4   mnth        610 non-null    int64  
 5   hr          610 non-null    int64  
 6   holiday     610 non-null    bool   
 7   weekday     610 non-null    int64  
 8   weathersit  610 non-null    int64  
 9   temp        610 non-null    float64
dtypes: bool(1), float64(1), int64(7), object(1)
memory usage: 43.6+ KB


# *Checking for Null Values in Dataset_1*

In [13]:
dataset_1.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

# Dataset 2

In [14]:
dataset_2=pd.read_excel("dataset_2.xlsx")

In [15]:
dataset_2

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [16]:
dataset_2.head()

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81        0.0       3          13   16
1           1        2  0.2727  0.80        0.0       8          32   40
2           2        3  0.2727  0.80        0.0       5          27   32
3           3        4  0.2879  0.75        0.0       3          10   13
4           4        5  0.2879  0.75        0.0       0           1    1

In [17]:
dataset_2.tail()

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

#  *Checking Dimension of Dataset of dataset_2*

In [18]:
dataset_2.shape

(610, 8)

In [19]:
dataset_2.shape[0] # Provide only the number of rows

610

In [20]:
dataset_2.shape[1] # Provide only the number of rows

8

# *Datetype of Dataset_1*

In [22]:
dataset_2.dtypes

Unnamed: 0      int64
instant         int64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

# *Unique values of Dataset_2*

In [23]:
dataset_2['windspeed'].unique()

array([0.    , 0.0896, 0.2537, 0.2836, 0.2985, 0.194 , 0.2239, 0.1343,
       0.1642, 0.3284, 0.4478, 0.3582, 0.4179, 0.3881, 0.1045, 0.4925,
       0.5522, 0.4627, 0.5224, 0.5821])

In [24]:
dataset_2['casual'].unique()

array([ 3,  8,  5,  0,  2,  1, 12, 26, 29, 47, 35, 40, 41, 15,  9,  6, 11,
        4,  7, 16, 20, 19, 10, 13, 14, 18, 17, 21, 33, 23, 22, 24])

In [25]:
dataset_2['atemp'].unique()

array([0.2879, 0.2727, 0.2576,    nan, 0.3485, 0.3939, 0.3333, 0.4242,
       0.4545, 0.4394, 0.4091, 0.2273, 0.2121, 0.197 , 0.1364, 0.1061,
       0.1212, 0.1667, 0.1818, 0.2424, 0.1515, 0.3182, 0.0606, 0.0758,
       0.0909, 0.303 , 0.0303, 0.0455, 0.    , 0.0152])

# *Summary of Datatype_2*

In [26]:
dataset_2.describe()

Unnamed: 0     instant       atemp         hum   windspeed      casual  \
count  610.000000  610.000000  599.000000  610.000000  610.000000  610.000000   
mean   304.500000  305.500000    0.199935    0.562475    0.204851    4.501639   
std    176.236111  176.236111    0.078836    0.175440    0.121806    6.319945   
min      0.000000    1.000000    0.000000    0.210000    0.000000    0.000000   
25%    152.250000  153.250000    0.151500    0.432500    0.104500    0.000000   
50%    304.500000  305.500000    0.197000    0.520000    0.194000    2.000000   
75%    456.750000  457.750000    0.242400    0.690000    0.283600    6.000000   
max    609.000000  610.000000    0.454500    1.000000    0.582100   47.000000   

       registered         cnt  
count  610.000000  610.000000  
mean    51.068852   55.570492  
std     47.021204   49.316802  
min      0.000000    1.000000  
25%     14.000000   16.000000  
50%     43.000000   47.000000  
75%     70.000000   79.750000  
max    247.000000  249.000000

In [27]:
dataset_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  610 non-null    int64  
 1   instant     610 non-null    int64  
 2   atemp       599 non-null    float64
 3   hum         610 non-null    float64
 4   windspeed   610 non-null    float64
 5   casual      610 non-null    int64  
 6   registered  610 non-null    int64  
 7   cnt         610 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 38.3 KB


# *Checking for Null Values in Dataset_2*

In [28]:
dataset_2.isnull().sum()

Unnamed: 0     0
instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

# *Droping unnecessary columns from Dataset_2*

In [29]:
dataset_2.drop(['Unnamed: 0'],axis=1)

instant   atemp   hum  windspeed  casual  registered  cnt
0          1  0.2879  0.81     0.0000       3          13   16
1          2  0.2727  0.80     0.0000       8          32   40
2          3  0.2727  0.80     0.0000       5          27   32
3          4  0.2879  0.75     0.0000       3          10   13
4          5  0.2879  0.75     0.0000       0           1    1
..       ...     ...   ...        ...     ...         ...  ...
605      606  0.2121  0.93     0.1045       0          30   30
606      607  0.2121  0.93     0.1045       1          28   29
607      608  0.2121  0.93     0.1045       0          31   31
608      609  0.2727  0.80     0.0000       2          36   38
609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 7 columns]

# *Merging Dataset 1 and 2*

In [30]:
Total_rentalcount = pd.merge(dataset_1, dataset_2, on='instant', how='inner') # Natural Join
Total_rentalcount

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  Unnamed: 0   atemp   hum  windspeed  casual  registered  cnt  
0    0.24           0  0.2879  0.81     0.0000       3          13   16  
1    0.22           1  0.2727  0.80     0.0000       8          32   40  
2    0.22           2  0.2727  0.80     0.0000       5          27   32  
3    0.24           3  0.2879  0.75     0.0000       3          10   13  
4    0.24           4  0.2879  0.75     0.0000       0           1    1  
..    ...         ...     ...   ...        ...     ...         ...  ...  
605  0.18         605  0.2121  0.93     0.1045       0          30   30  
606  0.18         606  0.2121  0.93     0.1045       1          28   29  
607  0.18         607  0.2121  0.93     0.1045       0          31   31  
608  0.22         608  0.2727  0.80     0.0000       2          36   38  
609  0.20         609  0.2576  0.86     0.0000       1          40   41  

[610 rows x 17 columns]